pip3 install -U --pre ovos_PHAL
pip3 install -U --pre ovos-phal-plugin-system
pip3 install -U --pre ovos-phal-plugin-connectivity-events
pip3 install -U --pre ovos-PHAL-plugin-ipgeo
pip3 install -U --pre ovos-PHAL-plugin-oauth
pip3 install -U --pre ovos-phal-plugin-color-scheme-manager
pip3 install -U --pre ovos-phal-plugin-gui-network-client
pip3 install -U --pre ovos-phal-plugin-wifi-setup
pip3 install -U --pre ovos-phal-plugin-network-manager
pip3 install -U --pre ovos-phal-plugin-dashboard
pip3 install -U --pre ovos-phal-plugin-notification-widgets
pip3 install -U --pre ovos-phal-plugin-gui-network-client
pip3 install -U --pre ovos-phal-plugin-balena-wifi
pip3 install -U --pre ovos-phal-plugin-brightness-control-rpi
pip3 install -U --pre ovos-phal-plugin-alsa
pip3 install -U --pre ovos-phal-plugin-gpsd
pip3 install -U --pre ovos-phal-plugin-analog-media-devices