pip3 install -U --pre ovos_plugin_common_play
pip3 install -U --pre ovos-ocp-deezer-plugin
pip3 install -U --pre ovos-ocp-youtube-plugin
pip3 install -U --pre ovos-ocp-m3u-plugin
pip3 install -U --pre ovos-ocp-bandcamp-plugin
pip3 install -U --pre ovos-ocp-rss-plugin
pip3 install -U --pre ovos-ocp-files-plugin
pip3 install -U --pre ovos-ocp-news-plugin
pip3 install -U --pre tutubo
pip3 install -U --pre yt-dlp
